### ISSUE TITLE
Flexed item doens't fill up it's container

### ISSUE THREAD

**Issue by JacobDB** [jonathantneal/flexibility#10]
On [this site](http://www.hoppycash.com/), I've up this script for IE9 and lower. It works pretty well, but I'm having an issue where each textbox's wrapper isn't stretching to fill it's container. See screenshots:

![container](https://cloud.githubusercontent.com/assets/1123997/11959890/73b5cac8-a895-11e5-997a-19a5cabe9b7a.png)

![item-label](https://cloud.githubusercontent.com/assets/1123997/11959893/77385de6-a895-11e5-92b3-b69699979337.png)

![item-input](https://cloud.githubusercontent.com/assets/1123997/11959895/799277ac-a895-11e5-8bf1-dfe613f9c32b.png)

Is `flex: 1 1 auto;` not supported yet? Would love to see a list of supported features.

**Comment by revxx14** [comment]
Just noticed the console error too, here's what that says:

![console-error](https://cloud.githubusercontent.com/assets/1123997/11959933/b52b34de-a895-11e5-86ce-9257d57b4e9a.png)

**Comment by jonathantneal** [comment]
Would you try this with Flexibility v1?

**Comment by jonathantneal** [comment]
If you can provide a test page, I will be happy to look into this. If we can’t test this with Flexibility v1, I’m going to close this issue.

**Comment by revxx14** [comment]
Sorry, thought I had responded to this. I updated the script to the most recent (v1.0.3) and it doesn't appear to be flexing at all now. You can view this at http://hoppycash.com/

**Comment by jonathantneal** [comment]
Flexibility v2 has rewritten all of this. Please do inspect the tests. https://rawgit.com/jonathantneal/flexibility/master/test/test.flexception.html

**Comment by JacobDB** [comment]
Nice, thanks!
