### ISSUE TITLE
Not an issue, I just want to thank you

### ISSUE THREAD

**Issue by Dan503** [jonathantneal/flexibility#25]
I couldn't find any way to message you directly so this was the next best thing.

An IE8/9 pollyfill for flexbox has been so sorely needed in the front end development industry but I thought I'd have to wait until the browsers were completely dead before I'd get to use flexbox without having to worry about legacy browser support.

With this pollyfill, it feels like Christmas has come early :D

This pollyfill frees us up to use flexbox as much as we like without those rusty old IE chains holding us back.

I've notified the entire team of Front Enders at our company about this and we're all super excited about the possibilities that this pollyfill gives us.

Thanks sooooo much for putting the effort into building this awesome pollyfill! :D

**Comment by eduardoboucas** [comment]
Sorry to hijack, but I feel exactly the same way. I felt genuinely happy when I saw this polyfill was released and I honestly believe it will be a game changer.

Thank you!

**Comment by Lageeek** [comment]
Full ack to the previous posts.

THANK YOU!

**Comment by tbaeg** [comment]
This is pure flippin' gold.

**Comment by af7** [comment]
This seems great, thank you!

May I ask if the **known issues** on this page are resolved?
http://caniuse.com/#feat=flexbox

Also this polyfiils IE8 and IE9, but the above page mentions also that IE10 has a non-latest version support on FlexBox. Does this polyfill also copes with the IE10 differences? 

Thank you.

**Comment by CreepGin** [comment]
Same with @af7 I also want to know if IE 10 and 11 are taken care of.

**Comment by jonathantneal** [comment]
I really appreciate this. I hope flexibility 2 is super solid and valuable for everyone.
