### ISSUE TITLE
IE8, IE9- node.currentStyle is null or not an object 

### ISSUE THREAD

**Issue by tporeba** [jonathantneal/flexibility#26]
I'm getting JS error when trying to use it in IE8 and IE9:

line: 1
char: 13551

**Comment by jonathantneal** [comment]
Would you please recreate this on [codepen](codepen.io) or your favorite code sharing service?

**Comment by psren** [comment]
I have the exact same error. @tporeba do you have a codepen already in place? If not i could do one.

**Comment by tporeba** [comment]
Here is what I tried to do: http://codepen.io/anon/pen/qbpQzv
Attached you may find a complete html file. 

I don't have real IE9 at hand now to confirm this example behaves exactly the same as my original attempt. IE9 emulation mode in IE11 doesn't give the same error. And this codepen thing seems to complain IE9 is not supported anyway. 

I can confirm and fix the example on Monday if necessary.
[test.html.txt](https://github.com/10up/flexibility/files/99804/test.html.txt)

**Comment by timkelty** [comment]
Having some of the same issues with certain markup. Can't reproduce consistently though.
In one case I had an element with `display: none`, if I removed that element _or_ the `display: none` style, the error went away.

**Comment by houguang** [comment]
经测试，ie10以下的浏览器都不兼容

<!DOCTYPE html>
<html ng-app>
<head>
<meta charset="utf-8">
<title></title>
<script src="flexibility.js" type="text/javascript" charset="utf-8"></script>
<style type="text/css">
* {margin: 0;padding: 0;}
.box {
	-js-display:flex;
	width: 600px;
	background: #ccc;
	display: flex;
	align-items:stretch;
	flex-direction:row;
	flex-wrap:wrap;
	justify-content:space-between;
}
.item {border: 1px solid #000;height: 200px;width: 100px;}
</style>
</head>
<body>
<div class="box">
	<div class="item">1</div>
	<div class="item">2</div>
	<div class="item">3</div>
	<div class="item">4</div>
</div>
</body>
</html>

**Comment by alexpts** [comment]
+1

**Comment by anwerso** [comment]
Can confirm this issue. Can reproduce it with adding inline `style="display: none;"` to a flex item. Problem appears here https://github.com/10up/flexibility/blob/master/lib/walk.js#L10-L12. Commenting out this lines will fix error, but guess we need proper way of handling hidden elements.

**Comment by Mitcheljager** [comment]
I am currently experiencing the same issue, however I do not have a flex element with `display: none; `directly on it. It does however contain an element with `display: none;`. As the previous comment suggested, I removed the line from flexibility.js. This does however force the hidden element to no longer be hidden.

**Comment by jonathantneal** [comment]
A check was required on `currentStyle` which is now in v2.
