### ISSUE TITLE
SVG elements throw error if present; cannot be flex children

### ISSUE THREAD

**Issue by timkelty** [jonathantneal/flexibility#29]
Testing in IE9 - Window 7, if any SVG is present, the following error is thrown:

```
SCRIPT5007: Unable to get value of the property '-js-display`: object is null or undefined
```

Any markup _following_ the svg fails to get any of the flexibility fixes applied.

E.g.
![screen shot 2016-01-25 at 12 09 05 pm](https://cloud.githubusercontent.com/assets/18329/12558342/03549556-c35d-11e5-85a8-8df51f122a63.png)

I created a test to recreate this: https://github.com/timkelty/flexibility/blob/master/tests/test-svg.html

**Comment by timkelty** [comment]
It seems the problem is your'e relying on `node.currentStyle` to be set, when it isn't for SVG elements/children.

Without being at all familiar withe code base, this seem to do the trick: https://github.com/timkelty/flexibility/commit/ff7c5d1f62da5738c094f8aa099199ae1572c777

**Comment by timkelty** [comment]
This error is relatively simple to circumvent: https://github.com/timkelty/flexibility/blob/master/lib/init.js#L15-L19

However, further problems occur with an SVG is the child of an element with `-js-display: flex`
Lots of properties that the code is expecting to be set aren't, throwing lots of errors.

**Comment by collin-garvey** [comment]
+1 I ran into this as well. Will probably turn out to be a common issue given the growing popularity of inline SVGs.

**Comment by zslabs** [comment]
Know everyone hates +1's, but also receiving this error using `<svg><use xlink:href="#heart"></svg>`

**Comment by jonathantneal** [comment]
Yes. I am on it. I was working on new features, but I need to stop and cover this first. For the record, I’m not entirely against the +1 ping. Everybody is different.

**Comment by puyol5** [comment]
Same here using `<svg><use xlink:href="#heart"></svg>`. +1. :) Thanks!

**Comment by nailliK** [comment]
I am experiencing the same problem.

**Comment by gijsroge** [comment]
Same problem here. :D

**Comment by SndrL** [comment]
Problem still persists.
Testing `IE9` on `windows 7`

**Comment by chapeljuice** [comment]
+1 I'm running into this issue now. Using the "solution" @timkelty provided above for now.

**Comment by jonathantneal** [comment]
Hurray, the SVG issue has been resolved in v2! https://rawgit.com/jonathantneal/flexibility/master/test/svg.html
