### ISSUE TITLE
v1.0.6 missing on npm registry

### ISSUE THREAD

**Issue by PeterDaveHello** [jonathantneal/flexibility#30]
There is a 1.0.6 tag on GitHub but only v1.0.5 been published on npm.

**Comment by ljharb** [comment]
Please run `npm publish`? Things not on `npm` can't be properly consumed.

**Comment by jonathantneal** [comment]
I’ve moved ahead to v2. Please use this version.

**Comment by ljharb** [comment]
@jonathantneal it would still be nice if you could publish v1.0.6 on a different tag than latest, just so it's fully published :-/

**Comment by jonathantneal** [comment]
Is it possible to publish a 1x branch after publishing a 2x?

**Comment by ljharb** [comment]
@jonathantneal absolutely! `git checkout v1.0.6 && npm publish --tag=1.x`, for example, will publish without overriding the "latest" tag.
