### ISSUE TITLE
flex-basis workaround

### ISSUE THREAD

**Issue by mosne** [jonathantneal/flexibility#41]
hello,
I'm making my grid system http://mosne.it/playground/mosne-flexbox/
and is working good! So first of all thank you! 
I've found a workaround for supporting flex-basis: ie9 and ie10 need a specified width, 
starting from ie11 it has to be max-width
`.col-1-3{` flex: 0 0 33.333333333333%; max-width:33.333333333333%;}
.no-flexbox .col-1-3{ `width:33.333333333333%;}.`
I was wondering if it would be possible to integrate this in your polyfill walker
so i can make a smaller css. thank you

**Comment by jonathantneal** [comment]
I am working on adding `flex-basis` support. The math was insane. Then I was swamped with work. I’m working on it this week.

**Comment by jonathantneal** [comment]
`flex-basis` support has arrived in v2!
