### ISSUE TITLE
Crashes (currentStyle: object is null or undefined) on IE9 if there is a hidden child element

### ISSUE THREAD

**Issue by corgrath** [jonathantneal/flexibility#50]
IE9 crashes with follow error message

The browser is Swedish, so the error message is also in Swedish, but it says the `currentStyle: object is null or undefined`.

```
SCRIPT5007: Det går inte att hämta värdet för egenskapen currentStyle: objektet är null eller odefinierat 
flexibility2.js?_rtv=033839933, rad 1 tecken 13792
```

A simple test case for this is:

```
.christoffer-flex {
    -js-display: flex;
}
.christoffer-hide {
    display: none;
}

<div class="christoffer-flex">
    <div class="christoffer-hide">hello world</div>
</div>
```

**Comment by corgrath** [comment]
Here is a test case

https://dl.dropboxusercontent.com/u/8183146/temp_netset/flexbox.html

**Comment by mahboob-awan** [comment]
Also getting the same error

SCRIPT5007: Unable to get value of the property 'currentStyle': object is null or undefined 
flexibility.generated.js?_rtv=461149466, line 9 character 13792

**Comment by mahboob-awan** [comment]
It will fix after #52

**Comment by corgrath** [comment]
Yes, my test case works with the fix

https://dl.dropboxusercontent.com/u/8183146/temp_netset/flexbox.mahboob.html

**Comment by jonathantneal** [comment]
These errors and the ones related to SVGs will be resolved in the next release. They cannot access the current style of the element, so they are failing. I am now working on this.

**Comment by jonathantneal** [comment]
Hurray, the SVG issue has been resolved in v2! https://rawgit.com/jonathantneal/flexibility/master/test/svg.html
