### ISSUE TITLE
IE8 & IE9 not working

### ISSUE THREAD

**Issue by WhateverMyNameIs** [jonathantneal/flexibility#51]
Hi, 

I have implemented a simple layout using bootstrap 4 flexible grid system. I have used the postCSS to add the -js-display: flex; before each display: flex;, I have the script included in my pages. When I simulate the IE 8&9 or even go to a virtual machine with IE 8&9, it doesn't work. The columns that were previously aligned in a row are now stacked under each other. 

There is a simple pen showing the layout and styles. 
http://codepen.io/anon/pen/JXpNpZ

What am I doing wrong that it doesn't work for me at all? Thank you for your help!

**Comment by iamclydehoel** [comment]
I've got the same issue. First time using this polyfill so I may be doing something wrong, but I've included the script on the page, and -js-display: flex before display: flex.

**Comment by WhateverMyNameIs** [comment]
No response at all? Anyone?

**Comment by jonathantneal** [comment]
The `flex` shorthand that you used leverages `flex-basis` which is not yet supported. I have been swamped, but as of today, I will have some time to work on getting these things supported. :)

**Comment by WhateverMyNameIs** [comment]
Those are amazing news! Thank you for your time!
Would it be a solution for now to take all flex shorthands and replace them with
- flex-grow: value;
- flex-shrink: value;
- flex-basis: value;
?

**Comment by widoz** [comment]
Hi there,
But the flex-basis doesn't work in ie9?

**Comment by jonathantneal** [comment]
The remaining flex properties have been added in v2. Try it out!
