### ISSUE TITLE
Unminified Dist File

### ISSUE THREAD

**Issue by zrothauser** [jonathantneal/flexibility#56]
It would be helpful if the build process built both a minified and unminified file, for providing hosts such as WordPress VIP that minify JS files.

**Comment by jonathantneal** [comment]
Agreed! I’d like to move the compiled files into the root directory, as well, similar to what normalize.css / sanitize.css do.

**Comment by noahjohn9259** [comment]
var fs = require('fs');
var uglify = require('uglify-js').minify;
var pkg = require('./package');

fs.writeFileSync('dist/flexibility.js', [
	'/*! Flexibility ',
	pkg.version,
	' | ',
	pkg.license,
	' Licensed | github.com/',
	pkg.repository,
	' */\n',
	'(function () {',
	[
		'lib/core.js',
		'lib/vendor/array-prototype-for-each.js',
		'lib/vendor/css-layout.js',
		'lib/vendor/event-listener.js',
		'lib/detect.js',
		'lib/init.js',
		'lib/on-resize.js',
		'lib/update-flex-container-cache.js',
		'lib/update-flex-item-cache.js',
		'lib/update-length-cache.js',
		'lib/walk.js'
	].map(function (file) {
		return fs.readFileSync(file, 'utf8');
	}).join(''),
	'})()'
].join(''), 'utf8');

fs.writeFileSync('dist/flexibility.min.js', uglify([
	'/*! Flexibility ',
	pkg.version,
	' | ',
	pkg.license,
	' Licensed | github.com/',
	pkg.repository,
	' */\n',
	'(function () {',
	[
		'lib/core.js',
		'lib/vendor/array-prototype-for-each.js',
		'lib/vendor/css-layout.js',
		'lib/vendor/event-listener.js',
		'lib/detect.js',
		'lib/init.js',
		'lib/on-resize.js',
		'lib/update-flex-container-cache.js',
		'lib/update-flex-item-cache.js',
		'lib/update-length-cache.js',
		'lib/walk.js'
	].map(function (file) {
		return fs.readFileSync(file, 'utf8');
	}).join(''),
	'})()'
].join(''), {
	fromString: true
}).code, 'utf8');

**Comment by noahjohn9259** [comment]
replace the build.js with this to get unmified version

https://gist.github.com/noahjohn9259/0b0a354a5280c4c4e9f2f09d66bb71af

**Comment by jonathantneal** [comment]
If it’s used as a package, minified is fine. When testing, you can build flexibility uncompressed with a source map.
