### ISSUE TITLE
Image link missing

### ISSUE THREAD

**Issue by AndreaChiabotto** [jonathantneal/flexibility#65]
Hi, i was really interested on you project.
Sadly, the first image of the  is missing  , giving a 404 error in return.

**Comment by jonathantneal** [comment]
I’m sorry about that. We just transferred the repository last night. Gimme a few minutes to fix that.

**Comment by jonathantneal** [comment]
Okay, I’ve pushed v2. All of the links have been updated. FYI, I don’t use an image, presently. I’d rather wait until someone can make something pretty looking.
