### ISSUE TITLE
Error with Attach Event in Chrome and FF

### ISSUE THREAD

**Issue by pdiddles03** [jonathantneal/flexibility#66]
There is no document.attachEvent method in Chrome or Firefox.  I applied a remedy at the top of the file detecting support and replacing the method with the correct method like so:

`if(!document.attachEvent){ document.attachEvent = document.addEventListener; }`

I think this is a good idea even for future versions of browsers

**Comment by jonathantneal** [comment]
Hi there! I’m not using `attachEvent` in flexibility anymore. Are you using the latest version?
