### ISSUE TITLE
Bower cannot find 2.0.0, 2.0.1

### ISSUE THREAD

**Issue by dougc84** [jonathantneal/flexibility#67]
I think a simple `git push --tags` would resolve this - these versions do not appear in bower repos at the moment.  Thanks!

**Comment by jonathantneal** [comment]
Very true. Thank you, @dougc84 ! I need to automate this process.

**Comment by jonathantneal** [comment]
And v2.0.1 is tagged!

**Comment by dougc84** [comment]
Thanks @jonathantneal !  Works great.
