### ISSUE TITLE
"function expected" in Internet Explorer

### ISSUE THREAD

**Issue by JacobDB** [jonathantneal/flexibility#74]
I have no idea what's going on with this; every time I try to initialize the script I'm seeing "function expected" in the console. 

My script:

```
flexibility(document.body);
```

It's happening if I target specific divs too, so I don't think it's specific to trying to use `body`. I've tried including it at the top of the page, at the bottom, inside a `jQuery(document).ready()`, and it always returns this same error.

Any help would be appreciated.

**Comment by pietrovismara** [comment]
Anyone alive here?

@JacobDB Did you manage to understand what's the problem?

**Comment by JacobDB** [comment]
@pietrovismara I can't remember which project this was for, and looking back in my commit history for the days around when I posted this, I can't locate anything about it. I think it may have been fixed by an updated version of the script eventually. Sorry I don't recall more clearly, I'm closing this issue.
