### ISSUE TITLE
'currentStyle' get null on IE10

### ISSUE THREAD

**Issue by lmai5** [jonathantneal/flexibility#91]
Hello, 

I'm facing a problem in flexibility.js in which 'currentStyle' get null just on IE10. It does not happen on IE11 or Chrome, Firefox.
Does this library support IE10? Or it it a bug? 
I have also attach the screen capture.

Thanks.

![image](https://user-images.githubusercontent.com/6018147/28299742-f2cee12a-6bb5-11e7-80cc-b60dc585db48.png)

**Comment by pygy** [comment]
Hi @maihoanglai flexibility is AFAIK intended for IE 8 and 9. You can load it between conditional comments:

```HTML
<!--[if IE]>
<script src="./flexibility.js">
<![endif]-->
```

`if IE` is enough, since IE10+ don't understand conditional comments.

For IE10, you can use PostCSS and Autoprefixer.
